#!/bin/bash

# koha/mariadb password can be found at:
# /etc/koha/sites/allsaints/koha-conf.xml
# on pi02
# search for: `db_scheme` (and then look for 'pass')

# cli connection to koha_allsaints database:
# mysql -u koha_allsaints -p koha_allsaints --port 3306

# the pi02 sshd_config MUST allow remote tcp connections forwarding

ssh -f -N -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" \
 -L 127.0.0.1:3306:127.0.0.1:3306 stg@pi02
